### ISSUE TITLE
x, y, z values not processing correctly

### ISSUE THREAD

**Issue by drinckes** [sparkfun/MMA8452_Accelerometer#11]
The x, y, and z values as read from the MMA come as 2's complement 12-bit numbers, and are assigned directly to integers. At least on 32-bit systems (Teensy) this doesn't work correctly for negative G-values and they need to be converted into signed values.

One fix is to add the following lines after the assignment of x,y and z and before cx/cy/cz:

        // Convert the 2's complement 12-bit values to signed integers.
        x = (x >> 11) == 0 ? x : -1 ^ 0xFFF | x;
        y = (y >> 11) == 0 ? y : -1 ^ 0xFFF | y;
        z = (z >> 11) == 0 ? z : -1 ^ 0xFFF | z;

**Comment by jimblom** [comment]
Should be solved with the latest merge.
