### ISSUE TITLE
Hangs when using 2 accelerometers

### ISSUE THREAD

**Issue by clovismarcondes** [sparkfun/MMA8452_Accelerometer#13]
I´m using two accelerometers for a project but when using with ODR over 50 it keeps hanging after a few seconds operating. Apparently it is losing some data because just after checking the available() it freezes inside the read(). I tried to replace the WIRE library for the I2C I founded on another issue thread and it seems to be working now. Is this approach correct?

**Comment by nseidle** [comment]
RTFM. MMA8452Q has two addresses it can be configured to.

**Comment by bboyho** [comment]
This looks like a stale issue and it might have been due to two devices using the same address on the I2C bus. I'm closing this out. 

If you are still having issues, we can reopen this issue but you may want to contact our [technical support team](https://www.sparkfun.com/technical_assistance).
