### ISSUE TITLE
No need to wait for data after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [sparkfun/MMA8452_Accelerometer#14]
In two places in SparkFun_MMA8452Q.cpp, there is a while-loop after the Wire.requestFrom() call. That while-loop is not needed.

When the Wire.requestFrom() function returns, the I2C transaction has completely finished and the received data is in the receive buffer in the Wire library. The Wire.read() only reads data from that buffer.

When there was a I2C bus error or I2C collision, there would be less bytes received, and that while-loop would halt the sketch.

**Comment by ToniCorinne** [comment]
Hi @Koepel  - thanks for all of your feedback on all of these libraries. If you'd like to open pull requests with the aforementioned fixes, we can test those and merge them in to make sure you get credit. 

Thanks!

**Comment by Koepel** [comment]
When writing new libraries, I hope Sparkfun will use the Arduino Wire library the way it is meant to be. My issues are there that when a library needs a change, that issue with the Wire library can be solved as well.

The issues will not return 'bad' data. For example a Wire.beginTransmission() before a Wire.requestFrom() does nothing. And a Wire.endTransmission() after Wire.requestFrom() puts the address on the I2C bus and the sensor acknowledges that. But that does not do any harm.

On the Arduino forums I'm seeing the wrong use of the Wire library so many times. That is why I made the issues here on Github. Many people copy the code or use it as an example. I don't need credits.

**Comment by chipmc** [comment]
So, Keopel, perhaps you can answer this question I have always had about the Sparkfun MMA8452 library - why can't you use the standard Wire library with interrupts?  The advanced example uses a different set of header files for i2c and not Wire.  Why?

Thank you,  Chip

**Comment by Koepel** [comment]
@chipmc, I don't know. Sparkfun uses direct low level I2C code with more sensors.

I prefer the Arduino Wire library, because bugs get fixed and it is (almost) the same for all the processors. It is interrupt driven, but the Wire.endTransmission() and Wire.requestFrom() wait until everything is finished. That is the way it works. It can not be changed without changing the complete Wire library. Maybe, someday, there will be a new and better Arduino library for I2C.

If you mean, why can't the Wire library be used inside one of your own interrupt service routines, that is because the Wire library uses interrupts itself.

**Comment by chipmc** [comment]
Koepel, I also prefer to use the standard libraries.  In the comments section of the [Sparkfun Advanced Example sketch](https://github.com/sparkfun/MMA8452_Accelerometer/blob/master/Firmware/MMA842Q%20Sketches/MMA8452Q_AdvancedExample/MMA8452Q_AdvancedExample.ino), there is the following explanation:

"Note: The MMA8452 is an I2C sensor, however this code does
 not make use of the Arduino Wire library. Because the sensor
 is not 5V tolerant, we can't use the internal pull-ups used
 by the Wire library. Instead use the included i2c.h, defs.h and types.h files."

I guess I was wondering what they meant by this or if there is - in fact - some limitation in the Wire library that prevents its use with a 3.3V sensor.

Thanks, Chip

**Comment by Koepel** [comment]
The Wire library enables the internal pullup resistors. For an Arduino Uno, that is about 50k to 5V. That could lift the voltage of SDA and SCL above the safe levels of the sensor.

The I2C voltage level problem can be avoided with a 3.3V board, or a 5V board with the SparkFun Logic Level Converter.

**Comment by nseidle** [comment]
Fixed in the main lib a long time ago. Pulled in with the [latest commit](https://github.com/sparkfun/MMA8452_Accelerometer/commit/6e89f22be1ebd0a3f7c8f7e80ac20189364d9b4e)

**Comment by Koepel** [comment]
In the file "MMA8452_Accelerometer/Firmware/MMA842Q Sketches/MMA8452Q_BasicExample/MMA8452Q_BasicExample.ino", there is still this wrong line:
```
while(Wire.available() < bytesToRead); //Hang out until we get the # of bytes we expect
```
and that is still copied by others.
Please remove that line.

Explanation: [Common-mistakes#1](https://github.com/Koepel/How-to-use-the-Arduino-Wire-library/wiki/Common-mistakes#1)

**Comment by nseidle** [comment]
Old firmware removed from repo.
