### ISSUE TITLE
Hangs on Leonardo

### ISSUE THREAD

**Issue by Scott216** [sparkfun/MMA8452_Accelerometer#4]
For some reason when using this accelerometer with a Leonardo the Leonardo hangs after a few seconds.  I tried it with an Uno and it was fine.  As a solution I got rid of Wire.h library and used this library instead: http://github.com/DSSCircuits/I2C-Master-Library.  Works great now.

**Comment by nseidle** [comment]
This has been fixed with the Wire changes to Arduino v1.6 and Arduino 1.8.
